export const vocals = [
  new Howl({src: ['melodies/billie_1.m4a']}),
  new Howl({src: ['melodies/billie_2.m4a']}),
  new Howl({src: ['melodies/man_4.m4a']}),
  new Howl({src: ['melodies/billie_4.m4a']}),
  new Howl({src: ['melodies/billie_5.m4a']}),
  new Howl({src: ['melodies/billie_6.m4a']}),
  new Howl({src: ['melodies/man_2.m4a']}),
  new Howl({src: ['melodies/billie_8.m4a']}),
  new Howl({src: ['melodies/billie_9.m4a']}),
  new Howl({src: ['melodies/billie_10.m4a']}),
  new Howl({src: ['melodies/rock_1.m4a']}),
  new Howl({src: ['melodies/rock_2.m4a']}),
  new Howl({src: ['melodies/rock_3.m4a']}),
  new Howl({src: ['melodies/rock_4.m4a']}),
  new Howl({src: ['melodies/man_5.m4a']}),
  new Howl({src: ['melodies/rock_6.m4a']}),
  new Howl({src: ['melodies/rock_7.m4a']}),
  new Howl({src: ['melodies/man_3.m4a']}),
  new Howl({src: ['melodies/rock_9.m4a']}),
  new Howl({src: ['melodies/man_1.m4a']}),
  new Howl({src: ['melodies/rock_11.m4a']}),
  new Howl({src: ['melodies/rock_12.m4a']}),
  new Howl({src: ['melodies/rock_13.m4a']}),
  new Howl({src: ['melodies/rock_14.m4a']}),
  new Howl({src: ['melodies/rock_15.m4a']}),
  new Howl({src: ['melodies/rock_16.m4a']}),
  new Howl({src: ['melodies/man_6.m4a']}),
  new Howl({src: ['melodies/rock_18.m4a']}),
  new Howl({src: ['melodies/rock_19.m4a']}),
  new Howl({src: ['melodies/rock_20.m4a']}),
];

export const keys = [
  "q", "w", "e", "r", "t", "y", "u", "i", "o", "p",
  "a", "s", "d", "f", "g", "h", "j", "k", "l", ";",
  'z', 'x', 'c', 'v', 'b', 'n', 'm'
];
